server {
    listen 127.0.0.1:444 ssl http2;
    server_name {{SOURCE_DOMAIN}};

    set $source_domain "{{SOURCE_DOMAIN}}";
    set $target_domain "{{TARGET_DOMAIN}}";

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;
    ssl_ecdh_curve X25519MLKEM768:X25519:secp384r1:prime256v1;
    ssl_stapling on;
    ssl_stapling_verify on;

    access_log off;
    error_log /dev/null;

    location / {
        return 301 https://$target_domain$request_uri;
    }
}

server {
    listen unix:/dev/shm/nginx/nginx.sock ssl http2;
    server_name {{SOURCE_DOMAIN}};

    set $source_domain "{{SOURCE_DOMAIN}}";
    set $target_domain "{{TARGET_DOMAIN}}";

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;
    ssl_ecdh_curve X25519MLKEM768:X25519:secp384r1:prime256v1;
    ssl_stapling on;
    ssl_stapling_verify on;

    access_log off;
    error_log /dev/null;

    location / {
        return 301 https://$target_domain$request_uri;
    }
}

server {
    listen 127.0.0.1:9000;
    location /health {
        return 204;
    }
}